"""init

Revision ID: 9f1129209b18
Revises: 
Create Date: 2025-12-13 22:50:40.876777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1129209b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bande_id', sa.Integer(), nullable=False),
    sa.Column('semaine_production', sa.Integer(), nullable=False),
    sa.Column('poids_moyen', sa.Float(), nullable=True),
    sa.Column('morts_semaine', sa.Integer(), nullable=True),
    sa.Column('animaux_restants', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bande_id'], ['bandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bandes', schema=None) as batch_op:
        batch_op.drop_column('poids_moyen_actuel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids_moyen_actuel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.drop_table('animal_info')
    # ### end Alembic commands ###
