"""Add mode_utilise to MessageChatbot

Revision ID: c9f07f5f5aa9
Revises: 9f1129209b18
Create Date: 2025-12-15 11:03:37.698311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f07f5f5aa9'
down_revision = '9f1129209b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_chatbot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_utilise', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_chatbot', schema=None) as batch_op:
        batch_op.drop_column('mode_utilise')

    # ### end Alembic commands ###
