"""sync schema

Revision ID: ecbd3d76d2a6
Revises: 03f18170fd7c
Create Date: 2025-12-12 01:07:29.106980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbd3d76d2a6'
down_revision = '03f18170fd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids_moyen_actuel', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duree_jours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandes', schema=None) as batch_op:
        batch_op.drop_column('duree_jours')
        batch_op.drop_column('poids_moyen_actuel')

    # ### end Alembic commands ###
